### ISSUE TITLE
GLMAPI.PY报错

### ISSUE THREAD

**Issue by guguji2** [P1uviophile/simple_RAG_with_LLMs_API#3]
INFO:     Started server process [10156]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
INFO:     127.0.0.1:15287 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Anaconda3\envs\myst\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Anaconda3\envs\myst\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\Anaconda3\envs\myst\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "D:\Anaconda3\envs\myst\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\pycharmProject\pythonproject\giuhub项目复现\simple_RAG_with_LLMs_API\ComChatGLMAPI.py", line 14, in create_item
    json_post_raw = await request.json()
  File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\requests.py", line 242, in json
    self._json = json.loads(body)
  File "D:\Anaconda3\envs\myst\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\myst\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\envs\myst\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by P1uviophile** [comment]
> INFO: Started server process [10156] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit) INFO: 127.0.0.1:15287 - "POST / HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "D:\Anaconda3\envs\myst\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi result = await app( # type: ignore[func-returns-value] File "D:\Anaconda3\envs\myst\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in **call** return await self.app(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\fastapi\applications.py", line 1054, in **call** await super().**call**(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\applications.py", line 113, in **call** await self.middleware_stack(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\middleware\errors.py", line 187, in **call** raise exc File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\middleware\errors.py", line 165, in **call** await self.app(scope, receive, _send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\middleware\exceptions.py", line 62, in **call** await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette_exception_handler.py", line 62, in wrapped_app raise exc File "D:\Anaconda3\envs\myst\lib\site-packages\starlette_exception_handler.py", line 51, in wrapped_app await app(scope, receive, sender) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 715, in **call** await self.middleware_stack(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 735, in app await route.handle(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 288, in handle await self.app(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 76, in app await wrap_app_handling_exceptions(app, request)(scope, receive, send) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette_exception_handler.py", line 62, in wrapped_app raise exc File "D:\Anaconda3\envs\myst\lib\site-packages\starlette_exception_handler.py", line 51, in wrapped_app await app(scope, receive, sender) File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\routing.py", line 73, in app response = await f(request) File "D:\Anaconda3\envs\myst\lib\site-packages\fastapi\routing.py", line 301, in app raw_response = await run_endpoint_function( File "D:\Anaconda3\envs\myst\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function return await dependant.call(**values) File "D:\pycharmProject\pythonproject\giuhub项目复现\simple_RAG_with_LLMs_API\ComChatGLMAPI.py", line 14, in create_item json_post_raw = await request.json() File "D:\Anaconda3\envs\myst\lib\site-packages\starlette\requests.py", line 242, in json self._json = json.loads(body) File "D:\Anaconda3\envs\myst\lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) File "D:\Anaconda3\envs\myst\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "D:\Anaconda3\envs\myst\lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

你是不是改了什么代码？

错误信息表明在尝试解析 JSON 数据时发生了 JSONDecodeError，这通常意味着发送到服务器的数据不是有效的 JSON 格式。
